name             : kyverno
namespace        : kyverno
chart            : kyverno
repoURL       : https://kyverno.github.io/kyverno/
targetRevision          : 3.9.0
syncWave: "1"
# namespaceEnforcePrivileged: true