crds:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  customLabels:
    app.kubernetes.io/part-of: kyverno
grafana:
  enabled: true
prometheusRule:
  enabled: true
admissionController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack   # must match your kps Helm release name
backgroundController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
reportsController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
cleanupController:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack