alertmanager:
  enabled: false

grafana:
  enabled: true
  persistence:
    enabled: false # using configmaps for dashboards
  resources:
    requests: {cpu: 50m, memory: 256Mi}
    limits: {memory: 768Mi}
  grafana.ini:
    server:
      root_url: https://grafana.home.lynge.party

# talos specific settings... setting up later
kubeControllerManager: {enabled: false}
kubeScheduler: {enabled: false}
kubeEtcd: {enabled: false}
kubeProxy: {enabled: false}

prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    evaluationInterval: 60s
    retention: 10d
    retentionSize: 8GB
    resources:
      requests: {memory: 400Mi}
      limits: {memory: 1Gi}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false