name             : prometheus-stack
namespace        : prometheus-stack
chart            : kube-prometheus-stack
repoURL       : https://prometheus-community.github.io/helm-charts
targetRevision          : 88.6.3
syncWave: "0"