name             : crossplane
namespace        : crossplane
chart            : crossplane
repoURL       : https://charts.crossplane.io/stable
targetRevision          : 2.5.0-rc.0.49.g3d8d7c1ef
syncWave: "0"