dex:
  enabled: false

configs:
  params:
    server.insecure: true # Using http-route with cert-manager
  cm:
    url: https://argocd.home.lynge.party
    oidc.config: |
      name: Entra ID
      issuer: $argocd-oidc:issuer
      clientID: $argocd-oidc:clientId
      clientSecret: $argocd-oidc:clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
          value: "SecurityGroup"
      requestedScopes:
        - openid
        - profile
        - email
  rbac:
    policy.default: role:readonly
    scopes: '[roles, groups, email]'
    policy.csv: |
      g, Admin, role:admin
      g, Reader, role:readonly