apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-azuread
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: grafana-azuread
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: grafana-client-id
    - secretKey: client-secret
      remoteRef:
        key: grafana-client-secret
    - secretKey: tenant-id
      remoteRef:
        key: tenant-id