# example until secret management is implemented

#apiVersion: v1
#data:
#  client-id: xx
#  client-secret: yy
#  tenant-id: zz
#kind: Secret
#metadata:
#  name: grafana-azuread
#  namespace: kube-prometheus-stack
#type: Opaque