apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      tenantId: "df5e637f-45a0-46cb-bed6-ed30163eb1f7"
      vaultUrl: "https://kv-homelab-rja.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret