apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  interfaces:
    - ^enp+ # find with talosctl get links --nodes <nodename> #look for real mac address in open state and no kind
# Another approach is to use a list of regexes (in Golang format) with all the common naming schemes
#    - ^eth+
#    - ^enp+
#    - ^ens+
#    - ^wlan+
#    - ^vmbr+
#    - ^wlp+

  externalIPs: true
  loadBalancerIPs: true