apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  hostname: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "192.168.0.240/29"
      - "192.168.0.36/32"